### PR TITLE
Updates `ember-inflector` version

### PR DESCRIPTION
**Pull request by twokul**
Current version is [`1.3.1`](https://github.com/fivetanley/ember-inflector-bower/blob/master/bower.json#L3)

### CODE REVIEW

**Comment by samselikoff** [comment]
thx! @rwjblue, any reason you put 1.4.0?

**Comment by rwjblue** [comment]
@twokul / @samselikoff - ember-inflector is kinda messed up as an addon. As you can see 1.4.0 is available in the repo (see [here](https://github.com/stefanpenner/ember-inflector/tree/1.4.0)), but not on NPM or bower.

**Comment by samselikoff** [comment]
gotcha, went ahead and reverted. thanks.

**Comment by twokul** [comment]
@rwjblue @samselikoff  that's not the one available through bower, I don't think. [bower link](http://bower.io/search/?q=ember-inflector) and [repo link](https://github.com/fivetanley/ember-inflector-bower)

**Comment by rwjblue** [comment]
@twokul - Yes, that repo is pushing to bower, **but** the latest tag was not pushed to bower.  That is what I'm saying.

**Comment by twokul** [comment]
@rwjblue ok, re-read your comment

**Comment by samselikoff** [comment]
yah 1.4 doesn't work out of the box, user has to add to bower. I'll use 1.3 for now until next version is on bower.

**Comment by samselikoff** [comment]
Not sure why the travis build didn't fail though, is there a way to clear the cache each time?

**Pull request merged**
