### PR TITLE
Add createList tests

### PR DESCRIPTION
**Pull request by cibernox**
Showing some  :heart:  :heart:  for this awesome project

### CODE REVIEW

**Comment by samselikoff** [comment]
thanks man, much appreciated!!

Could we get one more for `createList allows attr overrides?

```js
server.loadFactories({
   contact: Factory.extend({name: 'Sam'})
 });

var sams = server.createList('contact', 3);
var links = server.createList('contact', 3, {name: 'Link'});

// assert...
```

**Comment by cibernox** [comment]
One sec

**Comment by cibernox** [comment]
Done

**Comment by cibernox** [comment]
No, wait

**Comment by cibernox** [comment]
Now yes

**Comment by samselikoff** [comment]
woot!

**Pull request merged**
